# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  gtm_id: 'GTM-MRDML2T'

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e77f8e034dd150682885272752707ddc5fa254c7f4d67db6237862021fcaa0d7f161061afea76c821428bdbde5a3b3a0b41be1da074b3015592df6f12b7c46b5
  fb_app_id: 1887768571443254
  fb_app_secret: e16d904baf8b26fe7716e498bc7be3ea

test:
  secret_key_base: 2468152fa819c7f2942a7e9219690b006742e9e2f9f94b5fbce7019a770cb6c2d7ace8a860438b0b8aa17e275bca8ec253a29c900c6c80703370dad756f79085
  fb_app_id: 1887768571443254
  fb_app_secret: e16d904baf8b26fe7716e498bc7be3ea
  
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  fb_app_id: <%= ENV["FB_APP_ID"] %>
  fb_app_secret: <%= ENV["FB_APP_SECRET"] %>
  sentry_dsn: <%= ENV["SENTRY_DSN"] %>
